services:
  seanime:
    image: ju1js/seanime:latest
    container_name: seanime
    environment:
      - SEANIME_SERVER_HOST=0.0.0.0
    ports:
      - "43211:43211"
    volumes:
      - ./config:/root/.config/Seanime
      - ./data:/data
    restart: unless-stopped